# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dive < Formula
  desc "A tool for exploring layers in a docker image"
  homepage "https://github.com/wagoodman/dive/"
  version "0.13.1"

  on_macos do
    on_intel do
      url "https://github.com/wagoodman/dive/releases/download/v0.13.1/dive_0.13.1_darwin_amd64.tar.gz"
      sha256 "04e4c1bac21be3aef99799cf0e470149a072ea4786be50718aa846cd13746523"

      def install
        bin.install "dive"
      end
    end
    on_arm do
      url "https://github.com/wagoodman/dive/releases/download/v0.13.1/dive_0.13.1_darwin_arm64.tar.gz"
      sha256 "38b7fa95a13e7f4d0b3060c875fe7427c2a0613ecff674bb45156eb34bca0b09"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wagoodman/dive/releases/download/v0.13.1/dive_0.13.1_linux_amd64.tar.gz"
        sha256 "0970549eb4a306f8825a84145a2534153badb4d7dcf3febd1967c706367c3d0e"

        def install
          bin.install "dive"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wagoodman/dive/releases/download/v0.13.1/dive_0.13.1_linux_arm64.tar.gz"
        sha256 "2fcd2cf20f634ccdb41efac44048b204bfc867c115641f37a7420693ed480a18"

        def install
          bin.install "dive"
        end
      end
    end
  end
end
