# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dive < Formula
  desc "A tool for exploring layers in a docker image"
  homepage "https://github.com/wagoodman/dive/"
  version "0.13.0"

  on_macos do
    on_intel do
      url "https://github.com/wagoodman/dive/releases/download/v0.13.0/dive_0.13.0_darwin_amd64.tar.gz"
      sha256 "83b6c2653521e3f6e9f4cbfa6678fd9974a66d455b76a1696c2ce8c2d4403718"

      def install
        bin.install "dive"
      end
    end
    on_arm do
      url "https://github.com/wagoodman/dive/releases/download/v0.13.0/dive_0.13.0_darwin_arm64.tar.gz"
      sha256 "b70b20f5dfc8e27b3bf403f5c78f726dcb1aae37f5da18a832d11cae2873609b"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wagoodman/dive/releases/download/v0.13.0/dive_0.13.0_linux_amd64.tar.gz"
        sha256 "19ed7a1cfc567897a0a1e0e47ed4bdf803b053519b4d3bec50663182495db716"

        def install
          bin.install "dive"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wagoodman/dive/releases/download/v0.13.0/dive_0.13.0_linux_arm64.tar.gz"
        sha256 "2fd82611e7b3064769b02fc8b9d38e896b98b93c95bec6a80b5d306fd1469e51"

        def install
          bin.install "dive"
        end
      end
    end
  end
end
